services:
  hmpai:
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - NET_BIND_SERVICE
    privileged: true
    stdin_open: true
    tty: true
    build:
      context: ../../
      dockerfile: ./master-thesis-code/docker/Dockerfile
    volumes:
      - ../../hmp-ai:/workspace/hmp-ai # First copy and install (see Dockerfile), then mount so changes are reflected
      - ../../hmp:/workspace/hmp # First copy and install (see Dockerfile), then mount so changes are reflected
      - ../../master-thesis-code:/workspace/master-thesis-code
      # - O:\Research\FSW\Research_data\PF\Leerstoel Stigchel\Rick Otter:/workspace/data
      # Add network disk volume for data here
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]